version: "3.9"
services:

# - Frontend

  coffee-frontend:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - coffee_laravel 
    links:
      - coffee-backend    
    depends_on:
        - mysql
        - php
  laravel-frontend:
    build:
      context: .
      dockerfile: laravel-php.dockerfile

# - Backend

  coffee-backend:
    image: nginx:1.21.3-alpine
    networks:
      - coffee_network
      - coffee_laravel      

  laravel-backend:
    build:
      context: .
      dockerfile: laravel-php.dockerfile

# - Database 
  coffee-database:
  	image: mariadb:10.5
  	environment:
  		MYSQL_DATABASE: laravel
  		MYSQL_USER: laravel
  		MYSQL_PASSWORD: secret
  		MYSQL_ROOT_PASSWORD: secret
  	networks:
        - coffee_network
  	volumes:
        - mysql:/var/lib/mysql #named volume inside docker

networks:
  coffee_laravel:
  coffee_network:
